language: node_js
install: skip
script: 'true'
deploy:
    provider: elasticbeanstalk
    access_key_id: <encrypted access_key_id>
    secret_access_key: <encrypted secret_access_key>
    bucket: <bucket>
    edge: true # opt in to dpl v2
